#--- Exercício 4  - Variáveis
#--- Imprima a tela de um itinerário de viagem
#--- O itinerário deve conter o ponto de partida e de destino
#--- O ponto de partida e de destino devem estar armazenados em variáveis
#--- Entre os dois pontos deve conter no mínimo 10 pontos de parada
#--- Cada item ponto de parada deve conter data, hora e descrição
#--- Cada ponto de parada, data, hora e descrição será uma variável.
#--- O itinerário deve conter cabeçalho com o título da viagem, que será uma variável
#--- Deve ser usado os caracteres de tabulação e quebra de linha

print ('='*70)
viagem = input ('Titulo da Viagem: ')
print('\n')
partida = input('Ponto de partida: ')
print('\n')
destino = input('Ponto de destino: ')
print('\n')
p1 = input('Parada1: ')
d1 = input('Data da parada:')
h1 = input('Horario da parada')
des1 = input('Descrição da parada:')
print('\n')
p2 = input('Parada2: ')
d2 = input('Data da parada:')
h2 = input('Horario da parada')
des2 = input('Descrição da parada:')
print('\n')
p3 = input('Parada1: ')
d3 = input('Data da parada:')
h3 = input('Horario da parada')
des3 = input('Descrição da parada:')
print('\n')
p4 = input('Parada1: ')
d4 = input('Data da parada:')
h4 = input('Horario da parada')
des4 = input('Descrição da parada:')
print('\n')
p5 = input('Parada1: ')
d5 = input('Data da parada:')
h5 = input('Horario da parada')
des5 = input('Descrição da parada:')
print('\n')
p6 = input('Parada1: ')
d6 = input('Data da parada:')
h16 = input('Horario da parada')
des6 = input('Descrição da parada:')
print('\n')
p7 = input('Parada1: ')
d7 = input('Data da parada:')
h7 = input('Horario da parada')
des7 = input('Descrição da parada:')
print('\n')
p8 = input('Parada1: ')
d8 = input('Data da parada:')
h8 = input('Horario da parada')
des8 = input('Descrição da parada:')
print('\n')
p9 = input('Parada1: ')
d9 = input('Data da parada:')
h9 = input('Horario da parada')
des9 = input('Descrição da parada:')
print('\n')
p10 = input('Parada1: ')
d10 = input('Data da parada:')
h10 = input('Horario da parada')
des10 = input('Descrição da parada:')