#--- Exercicio 4  - Variávies e impressão com interpolacão de string
#--- Imprima a tela de um itinerário de viagem
#--- O itinerário deve conter o ponto de partida e de destino
#--- Entre os dois pontos deve conter no minimo 10 pontos de parada
#--- Cada item deve conter data, hora e descrição
#--- O itineário deve conter cabeçalho com o título da viagem
#--- Os dados de cada ponto devem estar em variáveis
#--- Deve ser usado os caracteres de tabulação, quebra de linha e a função Format()

print('='*135)
print('PREENCHA O ITINERÁRIO DE VIAGEM')

partida = input('\nDigite o ponto de partida: ')
datapartida = input('Digite a data: ')
horapartida = input('Digite a hora: ')
descopartida = input('Descrição: ')
destino = input('\nDigite o ponto de destino: ')
datadestino = input('Digite a data: ')
horadestino = input('Digite a hora: ')
descdestino = input('Descrição: ')
p1 = input('\nDigite o primeiro ponto de parada: ')
datap1 = input('Digite a data: ')
horap1 = input('Digite a hora: ')
descp1 = input('Descrição: ')
p2 = input('\nDigite o segundo ponto de parada: ')
datap2 = input('Digite a data: ')
horap2 = input('Digite a hora: ')
descp2 = input('Descrição: ')
p3 = input('\nDigite o terceiro ponto de parada: ')
datap3 = input('Digite a data: ')
horap3 = input('Digite a hora: ')
descp3 = input('Descrição: ')
p4 = input('\nDigite o quarto ponto de parada: ')
datap4 = input('Digite a data: ')
horap4 = input('Digite a hora: ')
descp4 = input('Descrição: ')
p5 = input('\nDigite o quinto ponto de parada: ')
datap5 = input('Digite a data: ')
horap5 = input('Digite a hora: ')
descp5 = input('Descrição: ')
p6 = input('\nDigite o sexto ponto de parada: ')
datap6 = input('Digite a data: ')
horap6 = input('Digite a hora: ')
descp6 = input('Descrição: ')
p7 = input('\nDigite o sétimo ponto de parada: ')
datap7 = input('Digite a data: ')
horap7 = input('Digite a hora: ')
descp7 = input('Descrição: ')
p8 = input('\nDigite o oitavo ponto de parada: ')
datap8 = input('Digite a data: ')
horap8 = input('Digite a hora: ')
descp8 = input('Descrição: ')
p9 = input('\nDigite o nono ponto de parada: ')
datap9 = input('Digite a data: ')
horap9 = input('Digite a hora: ')
descp9 = input('Descrição: ')
p10 = input('\nDigite o décimo ponto de parada: ')
datap10 = input('Digite a data: ')
horap10 = input('Digite a hora: ')
descp10 = input('Descrição: ')
print('='*135)

print("\n" * 1000)

print('='*135)
print('ITINERÁRIO DE VIAGEM')
print('-'*135)
print(f'Partida: {partida}\nData de partida: {datapartida}\nHora de Partida: {horapartida}')
print('-'*135)
print(f'Primeira parada: {p1}\nData de partida: {datap1}\nHora de Partida: {horap1}')
print('-'*135)
print(f'Segunda parada: {p2}\nData de partida: {datap2}\nHora de Partida: {horap2}')
print('-'*135)
print(f'Terceira parada: {p3}\nData de partida: {datap3}\nHora de Partida: {horap3}')
print('-'*135)
print(f'Quarta parada: {p4}\nData de partida: {datap4}\nHora de Partida: {horap4}')
print('-'*135)
print(f'Quinta parada: {p5}\nData de partida: {datap5}\nHora de Partida: {horap5}')
print('-'*135)
print(f'Sexta parada: {p6}\nData de partida: {datap6}\nHora de Partida: {horap6}')
print('-'*135)
print(f'Sétima parada: {p7}\nData de partida: {datap7}\nHora de Partida: {horap7}')
print('-'*135)
print(f'Oitava parada: {p8}\nData de partida: {datap8}\nHora de Partida: {horap8}')
print('-'*135)
print(f'Nona parada: {p9}\nData de partida: {datap9}\nHora de Partida: {horap9}')
print('-'*135)
print(f'Décima parada: {p10}\nData de partida: {datap10}\nHora de Partida: {horap10}')
print('-'*135)
print(f'Destino: {destino}\nData de partida: {datadestino}\nHora de Partida: {horadestino}')
print('='*135)